# -*- coding: utf-8 -*-
"""module1(task2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VLxjp1Fsv6Wr62AWrSPK8zZU_LydStj9
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("Sales.csv")

df.head()

x = df.month_name
y = df.total_profit
plt.plot(x,y)

x = df.month_name
y = df.total_profit
plt.plot(x,y,color="blue",linestyle ="dotted",marker ="o",markerfacecolor ="yellow",linewidth = 5)
plt.legend("profit",loc ="upper right")
plt.xlabel("Month number")
plt.ylabel("Item Sold units number")

plt.pie(df.total_units,labels=x)

#22. Write a python Matplotlib program to plot y=x^2 (parabola) and add text "Parabola $Y = x^2$" in the 
 plot

import numpy as np
x = np.linspace(-50,50,100)
y = x**2
plt.plot(x,y)
plt.title("Parabola $Y = x^2$")
plt.show()

a=[1,2,3,4,5,6]
b=[16,23,24,25,90,32]
plt.bar(a,b)
plt.show()